language: python
python:
- 2.7
- 3.6
- 3.7
matrix:
  allow_failures:
  - python: 3.6
install:
- pip install nose
- pip install flake8
- pip install coveralls
script:
- flake8 --show-source poolmanager tests
- coverage run --source=poolmanager setup.py test
